const { src, dest, watch } = require('gulp');
const sass = require('gulp-sass');
const autoprefixer = require('gulp-autoprefixer');
const rename = require('gulp-rename');
const replace = require('gulp-replace');
const headerComment = require('gulp-header-comment');
const through2 = require('through2');

// uncomment to enable scss sourcemaps
// const sourcemaps = require('gulp-sourcemaps');

const themeSettings = {
  styleDir: './styles',
  assetDir: './assets',
}

const sassConfig = {
  outputStyle: 'expanded',
};

function scss(cb) {
  src(`${themeSettings.styleDir}/**/*.scss`)
    // uncomment to enable scss sourcemaps
    // .pipe(sourcemaps.init())

    // actually compile scss files
    .pipe(sass(sassConfig).on('error', sass.logError))

    // default autoprefixer
    .pipe(autoprefixer())

    // uncomment to enable scss sourcemaps
    // .pipe(sourcemaps.write())

    // add a .liquid extension to all compiled css files
    .pipe(rename(function (path) {
      path.extname = '.css.liquid';
    }))

    // replace "{{ and }}" with {{ and }} so Shopify can actually read
    // needs to be quoted initiallty otherwise scss won't compile
    .pipe(replace('"{{', '{{'))
    .pipe(replace('}}"', '}}'))

    // add a small comment to the top of the file
    .pipe(headerComment(`
      ---
      Warning: DO NOT edit this file.

      It is automatically compiled, any changes manually made will be lost during an update.
      ---
    `))

    // manually change timestamp to avoid a gulp bug
    // ref: https://github.com/Shopify/themekit/issues/607#issuecomment-455042157
    .pipe(through2.obj((chunk, enc, cb) => {
      let date = new Date();
      chunk.stat.atime = date;
      chunk.stat.mtime = date;
      cb(null, chunk);
    }))

    // write compiled scss files to shopify's asset directory
    .pipe(dest(`${themeSettings.assetDir}/`));

    cb();
}

exports.styleWatch = function(cb) {
  watch(`${themeSettings.styleDir}/**/*.scss`, scss);
  cb();
};

exports.default = scss;
