const { src, dest, watch } = require('gulp');
const sass = require('gulp-sass');
const autoprefixer = require('gulp-autoprefixer');
const rename = require('gulp-rename');
const replace = require('gulp-replace');
const headerComment = require('gulp-header-comment');
// const through2 = require('through2');

// uncomment to enable scss sourcemaps
// const sourcemaps = require('gulp-sourcemaps');

const sassConfig = {
  outputStyle: 'expanded',
};

function scss() {
  return src('./scss/**/*.scss')
    // need to init sourcemaps first to write them later
    // uncomment to enable scss sourcemaps
    // .pipe(sourcemaps.init())

    // actually compile scss files
    .pipe(sass(sassConfig).on('error', sass.logError))

    // default autoprefixer
    .pipe(autoprefixer())

    // write sourcemaps to compiled file
    // uncomment to enable scss sourcemaps
    // .pipe(sourcemaps.write())

    // add a .liquid extension to all compiled css files
    .pipe(rename(function (path) {
      path.extname = '.css.liquid';
    }))

    // replace "{{ and }}" with {{ and }} so Shopify can actually read
    // needs to be quoted initiallty otherwise scss won't compile
    .pipe(replace('"{{', '{{'))
    .pipe(replace('}}"', '}}'))

    // add a small comment to the top of the file
    .pipe(headerComment(`
      ---
      Warning: DO NOT edit this file.

      It is automatically compiled, any changes manually made will be lost during an update.
      ---
    `))

    // TODO this needs to be fixed
    // manually change timestamp to avoid a gulp bug
    // ref: https://github.com/Shopify/themekit/issues/607#issuecomment-455042157
    // .pipe(through2.obj((chunk, enc) => {
    //   let date = new Date();
    //   chunk.stat.atime = date;
    //   chunk.stat.mtime = date;
    // }))

    // write compiled scss files to shopify's asset directory
    .pipe(dest('./assets/'));
}

exports.styleWatch = function() {
  watch('scss/*.scss', scss);
};

exports.default = scss;
